### ISSUE TITLE
Url da api não está funcionando

### ISSUE THREAD

**Issue by tulio-fciencia** [DeveloperCielo/Webservice-3.0#1]
As Url´s https://sandbox.cieloecommerce.com.br/ e https://apiquerysandbox.cieloecommerce.com.br/ não estão funcionando.

**Comment by netojoaobatista** [comment]
Essa API não está liberada ainda, @tulio-fciencia.

**Comment by tulio-fciencia** [comment]
Obrigado pela resposta, existe alguma api em Produção com retorno em Json?

**Comment by netojoaobatista** [comment]
Por favor, veja a documentação [Checkout Cielo](https://developercielo.github.io/Checkout-Cielo/)

**Comment by erickmajor** [comment]
Boa tarde,

As Url´s https://sandbox.cieloecommerce.com.br/ e https://apiquerysandbox.cieloecommerce.com.br/ não estão funcionando novamente.

Poderiam verificar?
