### ISSUE TITLE
Download Certificado E-Commerce Cielo

### ISSUE THREAD

**Issue by haryoncaetano** [DeveloperCielo/Webservice-3.0#10]
Está ocorrendo o erro 404 ao clicar para fazer o download do certificado **Certificado E-Commerce Cielo**.

[http://developercielo.github.io/Webservice-3.0/attachment/cieloecommerce.cielo.com.br.crt](http://developercielo.github.io/Webservice-3.0/attachment/cieloecommerce.cielo.com.br.crt)

**Comment by netojoaobatista** [comment]
Por favor, faça download dos 3 certificados novamente:
