### ISSUE TITLE
API 3.0 - Server returned HTTP response code: 400

### ISSUE THREAD

**Issue by JonatasMSantos** [DeveloperCielo/Webservice-3.0#11]
Olá, estou desenvolvendo a integração API 3.0 Via REST, porém recebi:

`Server returned HTTP response code: 400 for URL: https://apisandbox.cieloecommerce.cielo.com.br/1/sales/` 

Gostaria de saber qual é o erro de formatação.
Poderia me ajudar?

Segue código da Requisição:

    public static void main(String[] args) {
        JSONObject corpo = new JSONObject();
        corpo.put("MerchantId", "5bf5b74b-2f4b-4738-92cd-dba738ab058a");
        corpo.put("MerchantKey", "JVFMTZCHFMYKJNSAPXMOUMJTQLDKWFOVKISZXOLK");
        corpo.put("RequestId", "1");
        corpo.put("MerchantOrderId", "445636");

        JSONObject customer = new JSONObject();
        customer.put("Name", "Comprador Teste");

        JSONObject payment = new JSONObject();
        payment.put("Type", "CreditCard");
        payment.put("Amount", 15700);
        payment.put("Currency", "BRL");
        payment.put("Country", "BRA");
        payment.put("Provider", "Simulado");
        payment.put("Installments", 1);

        JSONObject creditCard = new JSONObject();
        creditCard.put("CardNumber", "0000000000000001");
        creditCard.put("Holder", "Teste Holder");
        creditCard.put("ExpirationDate", "12/2021");
        creditCard.put("SecurityCode", "123");
        creditCard.put("Brand", "Visa");

        payment.put("CreditCard", creditCard);

        corpo.put("Customer", customer);
        corpo.put("Payment", payment);

        URL url;
        HttpURLConnection connection;
        BufferedReader bufferedReader;

        try {
            url = new URL("https://apisandbox.cieloecommerce.cielo.com.br/1/sales/");

            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type", "application/json; charset=utf-8");
            connection.setDoOutput(true);

            DataOutputStream jsonRequest = new DataOutputStream(connection.getOutputStream());

            jsonRequest.writeBytes(corpo.toString());
            jsonRequest.flush();
            jsonRequest.close();

            bufferedReader = new BufferedReader(new InputStreamReader(connection.getInputStream()));

            String responseLine;
            StringBuffer jsonResponse = new StringBuffer();

            while ((responseLine = bufferedReader.readLine()) != null) {
                jsonResponse.append(responseLine);
            }

            bufferedReader.close();

            connection.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

Segue Json Limpo gerado do código acima:

`{  
   "Payment":{  
      "Installments":1,
      "Type":"CreditCard",
      "Amount":15700,
      "Currency":"BRL",
      "Country":"BRA",
      "CreditCard":{  
         "CardNumber":"0000000000000001",
         "Brand":"Visa",
         "ExpirationDate":"12/2021",
         "Holder":"Teste Holder",
         "SecurityCode":"123"
      },
      "Provider":"Simulado"
   },
   "MerchantKey":"JVFMTZCHFMYKJNSAPXMOUMJTQLDKWFOVKISZXOLK",
   "RequestId":"1",
   "Customer":{  
      "Name":"Comprador Teste"
   },
   "MerchantId":"5bf5b74b-2f4b-4738-92cd-dba738ab058a",
   "MerchantOrderId":"445636"
}`

Desde já agradeço.

Código do Estabecimento: 1052171360 

Atenciosamente,

Jônatas.

**Comment by netojoaobatista** [comment]
@JonatasMSantos, você não está enviando as credenciais como cabeçalho HTTP; em vez disso, você está colocando suas credenciais no meio do corpo JSON.

Seus `MerchantId`, `MerchantKey` e `RequestId` devem ir como cabeçalhos HTTP; basicamente, seu código deverá ficar mais ou menos assim:

```java
JSONObject corpo = new JSONObject();
corpo.put("MerchantOrderId", "445636");

JSONObject customer = new JSONObject();
customer.put("Name", "Comprador Teste");

JSONObject payment = new JSONObject();
payment.put("Type", "CreditCard");
payment.put("Amount", 15700);
payment.put("Currency", "BRL");
payment.put("Country", "BRA");
payment.put("Provider", "Simulado");
payment.put("Installments", 1);

JSONObject creditCard = new JSONObject();
creditCard.put("CardNumber", "0000000000000001");
creditCard.put("Holder", "Teste Holder");
creditCard.put("ExpirationDate", "12/2021");
creditCard.put("SecurityCode", "123");
creditCard.put("Brand", "Visa");

payment.put("CreditCard", creditCard);

corpo.put("Customer", customer);
corpo.put("Payment", payment);

URL url;
HttpURLConnection connection;
BufferedReader bufferedReader;

try {
	url = new URL("https://apisandbox.cieloecommerce.cielo.com.br/1/sales/");

	connection = (HttpURLConnection) url.openConnection();
	connection.setRequestMethod("POST");
	connection.setRequestProperty("Content-Type", "application/json; charset=utf-8");
	connection.setRequestProperty("MerchantId", "seu-merchant-id");
	connection.setRequestProperty("MerchantKey", "seu-merchant-key");
	connection.setRequestProperty("RequestId", "identificador-da-requisição");
	
	connection.setDoOutput(true);

	DataOutputStream jsonRequest = new DataOutputStream(connection.getOutputStream());

	jsonRequest.writeBytes(corpo.toString());
	jsonRequest.flush();
	jsonRequest.close();

	bufferedReader = new BufferedReader(new InputStreamReader(connection.getInputStream()));

	String responseLine;
	StringBuffer jsonResponse = new StringBuffer();

	while ((responseLine = bufferedReader.readLine()) != null) {
		jsonResponse.append(responseLine);
	}

	bufferedReader.close();

	connection.disconnect();
} catch (Exception e) {
	e.printStackTrace();
}
```

**Comment by JonatasMSantos** [comment]
@netojoaobatista, Muito obrigado! Funcionou perfeitamente!

**Comment by CesarBarros** [comment]
Olá Pessoal, tudo bom?

Estou estuando a API da Cielo no PostMan, mas só me retorna o error 500.
Alguém sabe o que eu estou fazendo de errado? Segue os prints e a configuração que estou usando.

POST:
`https://apisandbox.cieloecommerce.cielo.com.br/1/sales/`

HEADERS:
```
MerchantId:b5fec8cb-0e78-4084-b7fb-6e5db6fc2ec6
MerchantKey:AMHWFDCXPIYSJRZYBPCELLFQABKRVXFVLTAQFZTS
RequestId:b5fec8cb-0e78-4084-b7fb-6e5db6fc2ec6
```

BODY:
```
MerchantOrderId:170620170001
Customer.Name:Cesar Barros
Customer.Status:NEW
Payment.Type:CreditCard
Payment.Amount:150057
//Payment.Provider:
Payment.Installments:1
CreditCard.CardNumber:1234123412341231
CreditCard.Holder:Cesar Barros
CreditCard.ExpirationDate:12/2030
CreditCard.SecurityCode:123
CreditCard.Brand:Visa
```

[PrintScreen - Error 500 como resposta](http://ap.imagensbrasil.org/image/0dZ25G
)
[PrintScreen - Informações no Header](http://ap.imagensbrasil.org/image/0dZB0K)
[PrintScreen - Informações no Body](http://ap.imagensbrasil.org/image/0dZ4vf
)

Desde já, agradeço a ajuda de todos.
