### ISSUE TITLE
Implementação PHP com API 3.0

### ISSUE THREAD

**Issue by Messhias** [DeveloperCielo/Webservice-3.0#16]
Bom dia galera,

 

Estou com um problema e umas dúvidas sobre a API 3.0 da CIELO, estou tentando fazer uma requisição de venda no ambiente de testes da sandbox e mesmo assim não consigo ter nenhum tipo de retorno.

 

Estou usando o framework codeigniter e to tentando fazer através de uma controller, algo basico e a aplicação ainda está no inicio de seu desenvolvimento.

 

Tentei tanto com PHP como Javascript:

 

Script PHP da controller (na minha tentativa com o PHP)

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Pagamento extends CI_Controller {

	public function index()
	{
		$url = 'https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/';
		$headers = array(
			'MerchantId' 	=> 'XXXXX-XXX-XXX-XXX-XXX',
			'MerchantKey' 	=>	'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
			'Content-Type'	=>	'Content-Type: application/json',
			'RequestId'		=>	rand(10,1000)
		);

		$data = array(
			"MerchantOrderId"=>rand(0,99999),
			"Customer"=>array(  
				"Name"=>"Comprador Teste"
		   ),
		);

		print_r($this->curl->submit_data($url,$data,$headers));

	}

}

/* End of file Checkout.php */
/* Location: ./application/controllers/Checkout.php */`

Aqui está o script da library que eu criei para ler cURL:

`<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Curl
{
	private $response;

	protected $ci;

	public function __construct()
	{
        $this->ci =& get_instance();
	}

	public function submit_data($url = '', $data = array(),$headers = array()){
		ini_set('max_execution_time', 300); 
		$ch = curl_init();
		$timeout = 500000;
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
		curl_setopt($ch, CURLOPT_POST, true);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data,true));
		$this->response = curl_exec($ch);
		curl_close($ch);

		return $this->response;
	}

	public function setResponse($response = ""){
		$this->response = $response;
	}

	public function getResponse(){
		return $this->response;
	}

}

/* End of file Curl_library.php */
/* Location: ./application/libraries/Curl_library.php */
` 

 

Achando que era um possivel problema de implementação minha no PHP eu criei uma uma requisição também com JQuery, porém, não obtive sucesso;

 

Javascript/JQuery:

`<script type="text/javascript">
		$(document).ready(function() {

			$.ajaxSetup({
			    beforeSend: function(xhr) {
			        xhr.setRequestHeader("MerchantId", 'XXXXXXX-XXXX-XXXX-XXX-XXXXXXXXXXXXX');
			        xhr.setRequestHeader('MerchantKey', "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
			        xhr.setRequestHeader('X-Requested-With','XMLHttpRequest')
			    }
			});

			$.ajax({
				url: 'https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/',
				type: 'POST',
				dataType: 'json',
        		contentType: 'application/json',
        		crossDomain:false,
				data: {
				},
				error:function(e,text,xhr) {
					console.log(e);	
				},
				complete:function(e,text,xhr){
					console.log(e);	
				}
			});
		});
	</script>
`

Com o cURL não me retorna nada, fica tudo em branco.

No Javascript na requisição do JQuery me volta apenas "error"

**Comment by netojoaobatista** [comment]
Com jQuery você não vai conseguir mesmo por causa do CORS. Agora, no PHP, você não está enviando os dados conforme a documentação: [Criando uma transação simples](https://developercielo.github.io/Webservice-3.0/#criando-uma-transação-simples)

**Comment by Messhias** [comment]
Fiz as alterações conforme pediu, ainda assim meu cURL nao retorna nada
```
<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Checkout extends CI_Controller {

	public function index()
	{
		$url = 'https=>//apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/';
		$headers = array(
			'MerchantId' 	=> 'xxxxxx-xxxx-xxxx-xxx-xxxxx',
			'MerchantKey' 	=>	'XXXXXXXXXXXXXXX',
			'Content-Type'	=>	'Content-Type: application/json',
			'RequestId'		=>	rand(10,1000)
		);

		$data = array(
			"MerchantOrderId"=>"2014111703",
		   		"Customer"=>array(
		      "Name"=>"Comprador Teste"
		   ),
		   "Payment"=>array(
		     "Type"=>"CreditCard",
		     "Amount"=>15700,
		     "Provider"=>"Simulado",
		     "Installments"=>1,
		     "CreditCard"=>aray(
		         "CardNumber"=>"1234123412341231",
		         "Holder"=>"Teste Holder",
		         "ExpirationDate"=>"12/2021",
		         "SecurityCode"=>"123",
		         "Brand"=>"Visa"
		     )
		   )
		);


		print_r($this->curl->submit_data($url,$data,$headers));

	}

}

/* End of file Checkout.php */
/* Location=> ./application/controllers/Checkout.php */
```

Link onde está hospedado a solução teste: https://gateway-race.bananagroove.com/checkout

**Comment by netojoaobatista** [comment]
Você precis isolar a integração do framework; nesse momento não sabemos se o problema está no framework ou na integração. 

Envie o JSON utilizando alguma ferramenta como [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop). Assim você conseguirá verificar se o JSON está correto segundo a documentação que lhe passei. Com o JSON correto, apenas converta-o para utilizar com sua ferramenta ou framework preferido.

**Comment by Messhias** [comment]
Ok, irei isolar e verificar e assim que possível posto um feedback, obrigado.
