### ISSUE TITLE
[0] => Operation timed out after 0 milliseconds with 0 out of 0 bytes received

### ISSUE THREAD

**Issue by webinclui** [DeveloperCielo/Webservice-3.0#2]
Seguinte erro ao processar a compra:

[0] => Operation timed out after 0 milliseconds with 0 out of 0 bytes received

Parece que a url de retorno não está configurada como null, porém, onde altero essa opção?

**Comment by netojoaobatista** [comment]
Erros de timeout são causados, em sua grande maioria das vezes, pelo não uso de TLS na requisição. É preciso que você verifique o uso de TLS ou em poste como está fazendo a requisição.
