### ISSUE TITLE
'Status => 0' com pagamento efetuado - Débito

### ISSUE THREAD

**Issue by assisjeferson** [DeveloperCielo/Webservice-3.0#21]
Realizei uma compra de teste, pois alguns pedidos ficavam como aguardando pagamento mesmo estando capturado no painel da Cielo.

Ao tentar consultar via API, o pedido de teste esta retornando o `Status => 0`, porém em minha conta foi debitado e no painel esta como `capturada`

Olhando a tabela de status na documentação, tem a seguinte descrição: "Falha ao processar o pagamento"

Se houve falha, qual motivo de algumas compras estarem sendo debitadas das contas dos clientes?

**Comment by netojoaobatista** [comment]
@assisjeferson, como exatamente está a resposta da consulta?

**Comment by assisjeferson** [comment]
Estava voltando da seguinte forma:

```
{
  "MerchantOrderId": "xxx",
  "Customer": {
    "Name": "Jeferson Assis",
    "Address": {}
  },
  "Payment": {
    "DebitCard": {
      "CardNumber": "xxx",
      "Holder": "Jeferson xxx",
      "ExpirationDate": "xx/2017",
      "Brand": "Master"
    },
    "Tid": "xxxx",
    "PaymentId": "246f4740-f7ea-4526-9dae-b3590ce77c1a",
    "Type": "DebitCard",
    "Amount": 100,
    "ReceivedDate": "2017-03-08 11:52:42",
    "Currency": "BRL",
    "Country": "BRA",
    "Provider": "Cielo",
    "ReturnCode": "0",
    "Status": 0,
    "Links": [
      {
        "Method": "GET",
        "Rel": "self",
        "Href": "https://apiquery.cieloecommerce.cielo.com.br/1/sales/246f4740-f7ea-4526-9dae-b3590ce77c1a"
      }
    ]
  }
}
```
Testei agora e o retorno veio o esperado, creio que quando aconteça deva ter algum delay até o sistema atualizar o status corretamente.

**Comment by netojoaobatista** [comment]
> creio que quando aconteça deva ter algum delay até o sistema atualizar o status corretamente.

Sim; a autorização é assíncrona; não necessariamente terá ocorrido simultaneamente com a resposta da requisição.

**Comment by assisjeferson** [comment]
Maravilha, vou tratar isso pois não tinha na documentação e fiquei perdido.

Muito obrigado.
