### ISSUE TITLE
Cancelamento de uma Transação

### ISSUE THREAD

**Issue by superainovacoes** [DeveloperCielo/Webservice-3.0#22]
Se por ventura algum erro acontecer em minha aplicação e eu não conseguir salvar o resultado de um cancelamento de uma transação/captura (e o cancelamento tiver sido efetuado pela api) e eu reenviar a requisição de cancelamento obtenho o retorno "309 - Transaction not available to void".

Se eu realizar a consulta da transação ela me retorna que está cancelada mas nesse caso precisaria fazer sempre duas requisições. 

Qual a possibilidade de retornar outro código dizendo que a transação/captura já está cancelada?

**Comment by netojoaobatista** [comment]
> Qual a possibilidade de retornar outro código dizendo que a transação/captura já está cancelada?

Não compreendi. Se ocorreu um erro na sua aplicação, você não conseguirá ter um retorno de qualquer forma; nesse caso, só fazendo uma requisição de consulta para verificar se a transação foi cancelada.

Chegou a cadastrar uma [URL de Notificação](https://developercielo.github.io/Webservice-3.0/#url-de-notificação)? Talvez, se o erro ocorrido em sua aplicação for pontual e apenas momentâneo, a notificação talvez possa ajudá-lo.

**Comment by superainovacoes** [comment]
Não tinha visto essa url de notificação, falta uma documentação para saber o que e como ela envia as informações.

Mas de qualquer forma, alguma instabilidade no processo de gravar/pegar o retorno do cancelamento poderia acontecer (mas esperamos que não).

Apenas seria mais fácil ter o retorno que já foi cancelado, se realmente está cancelado na segunda requisição. 

Até porque a mensagem de erro nessa segunda requisição é descrita como "Transação não pode ser Cancelada - Entre em contato com o suporte Cielo" - evitaria ligações ao 0800.

**Comment by netojoaobatista** [comment]
> Apenas seria mais fácil ter o retorno que já foi cancelado, se realmente está cancelado na segunda requisição.

Nesse tipo de cenário você deve fazer uma [consulta](https://developercielo.github.io/Webservice-3.0/#consultando-uma-venda).
