### ISSUE TITLE
Provider is not supported for this Payment Type

### ISSUE THREAD

**Issue by loja5combr** [DeveloperCielo/Webservice-3.0#3]
Na opção de teste para TEF nenhum dos bancos disponíveis está funcionando em sandbox.

**Comment by netojoaobatista** [comment]
A API é para transações no e-commerce. Você está tentando integrar com TEF?

**Comment by loja5combr** [comment]
Sim, o Pagamento por Transferência Eletrônica.

Json
{"MerchantOrderId":"123456","Customer":{"Name":"tef de teste"},"Payment":{"Type":"EletronicTransfer","Amount":"10055","Provider":"Bradesco","ReturnUrl":"https:\/\/www.loja5.com.br"}}

Resposta:
  {
    "Code": 133,
    "Message": "Provider is not supported for this Payment Type"
  }
