### ISSUE TITLE
PostMan Error 500

### ISSUE THREAD

**Issue by CesarBarros** [DeveloperCielo/Webservice-3.0#31]
Olá Pessoal, tudo bom?

Estou estuando a API da Cielo no PostMan, mas só me retorna o error 500.
Alguém sabe o que eu estou fazendo de errado? Segue os prints e a configuração que estou usando.

POST:
`https://apisandbox.cieloecommerce.cielo.com.br/1/sales/`

HEADERS:
```
MerchantId:b5fec8cb-0e78-4084-b7fb-6e5db6fc2ec6
MerchantKey:AMHWFDCXPIYSJRZYBPCELLFQABKRVXFVLTAQFZTS
RequestId:b5fec8cb-0e78-4084-b7fb-6e5db6fc2ec6
```

BODY:
```
MerchantOrderId:170620170001
Customer.Name:Cesar Barros
Customer.Status:NEW
Payment.Type:CreditCard
Payment.Amount:150057
//Payment.Provider:
Payment.Installments:1
CreditCard.CardNumber:1234123412341231
CreditCard.Holder:Cesar Barros
CreditCard.ExpirationDate:12/2030
CreditCard.SecurityCode:123
CreditCard.Brand:Visa
```

[PrintScreen - Error 500 como resposta](http://ap.imagensbrasil.org/image/0dZ25G
)
[PrintScreen - Informações no Header](http://ap.imagensbrasil.org/image/0dZB0K)
[PrintScreen - Informações no Body](http://ap.imagensbrasil.org/image/0dZ4vf
)

Desde já, agradeço a ajuda de todos.

**Comment by CesarBarros** [comment]
Ninguém faz ideia de como solucionar isso?
Tem alguém que ainda da suporte para essa API ou ela não funciona porque foi descontinuada e ninguém mais da atenção/suporte?

Um abraço a todos

**Comment by netojoaobatista** [comment]
Você tem que enviar um JSON, exatamente como descrito no manual: https://developercielo.github.io/Webservice-3.0/
