### ISSUE TITLE
Servidor remoto retornando erro 400

### ISSUE THREAD

**Issue by felipeejunges** [DeveloperCielo/Webservice-3.0#32]
Olá, estou tentando desenvolver a comunicação com a API 3.0 com VB.NET, mas na parte de comunicação com o servidor, estou tendo problemas para transação simples.

Tentei de ambas as formas:
Primeira:

`

    Public Function postDados(json As String, baseUrl As String, postUrl As String, merchant As Merchant) As String
        Dim urlPost As String = baseUrl & postUrl

        Dim webClient As New WebClient()
        Dim resByte As Byte()
        Dim jsonVolta As String
        Dim reqByte() As Byte

        Dim teste = "teste"
        Try
            webClient.Headers("content-type") = "application/json"
            webClient.Headers("MerchantId") = merchant.id
            webClient.Headers("MerchantKey") = merchant.key

            reqByte = Encoding.Default.GetBytes(json)
            jsonVolta = webClient.UploadString(urlPost, json)
            resByte = webClient.UploadData(urlPost, "post", reqByte)
            jsonVolta = Encoding.Default.GetString(resByte)
            webClient.Dispose()
        Catch ex As Exception
            Throw ex
        End Try

        Return jsonVolta
    End Function

`

Segunda:
`

    Public Function postDados2(json As String, baseUrl As String, postUrl As String, merchant As Merchant) As String
        Dim urlPost As String = baseUrl & postUrl
        Dim jsonVolta As String

        Try
            Dim request As WebRequest = WebRequest.Create(urlPost)
            request.Method = "POST"
            request.ContentType = "application/json"
            request.Headers("MerchantId") = merchant.id
            request.Headers("MerchantKey") = merchant.key

            Using writer = New StreamWriter(request.GetRequestStream())
                writer.Write(json)
                writer.Close()
            End Using

            Dim response As HttpWebResponse = DirectCast(request.GetResponse(), HttpWebResponse)
            jsonVolta = response.ToString
        Catch ex As Exception
            Throw ex
        End Try

        Return jsonVolta
    End Function

`

Valor urlPost: https://apisandbox.cieloecommerce.cielo.com.br/1/sales/
Valor Json: 
> "{""MerchantOrderId"":""1234123"",""Customer"":{""name"":""teste""},""Payment"":{""Type"":""CreditCard"",""Amount"":1.0,""Installments"":1,""SoftDescriptor"":"""",""CreditCard"":{""CardNumber"":""12312312"",""Holder"":""teste"",""ExpirationDate"":""2022-12-12"",""SecurityCode"":""1212"",""Brand"":""Visa""}}}"

Obs: O json é gerado automaticamente pelo newtonsoft

**Comment by netojoaobatista** [comment]
@felipeejunges, se o seu json está chegando dessa forma aí, então ele é inválido. Você precisa arrumar esse json antes de enviar para a API. Como está gerando esse json com o newtonsoft?

**Comment by felipeejunges** [comment]
Com esta função:
`

    Public Function converterJson(pedido As Pedido) As String
        ' Setando configurações do Json
        ' 1 Configuração: Remover Nullos
        ' 2 Configuração: Não colocar valores default (usando a 2)
        Dim configuracao = New JsonSerializerSettings
        'configuracao.NullValueHandling = NullValueHandling.Ignore
        configuracao.DefaultValueHandling = DefaultValueHandling.Ignore
        Dim json As String = Newtonsoft.Json.JsonConvert.SerializeObject(pedido, configuracao)
        Return json
    End Function

`

**Comment by felipeejunges** [comment]
E caso eu desconverta ele, utilizando o deserialize, funciona normalmente.
Eu uso esta função:

`
    Public Function desconverterJson(json As String) As Pedido
        Dim pedido As Pedido = Newtonsoft.Json.JsonConvert.DeserializeObject(Of Pedido)(json)
        Return pedido
    End Function

`

**Comment by felipeejunges** [comment]
![testando com soapui](https://user-images.githubusercontent.com/20795458/29790050-a94679d6-8c0e-11e7-9782-f9d55320798a.png)

Então, testei o meu Json com o SOAPUI ui para se comunicar com o Webservice e não recebi erro 400 e sim uma resposta json.

**Comment by netojoaobatista** [comment]
Além das aspas duplicadas que invalidam o json, você ainda está enviando a data no formato inválido. Você está enviando `"ExpirationDate":"2022-12-12"` e precisa enviar `"ExpirationDate":"12/2022"`. Arrume a data e também o json que irá funcionar.

**Comment by netojoaobatista** [comment]
@felipeejunges, para facilitar as coisas aí, faça a requisição no postman: https://developercielo.github.io/Tutorial/Postman

**Comment by felipeejunges** [comment]
Bem, aparentemente é mesmo as aspas duplas e a data. Alterei na mão no SoapUi e funcionou.

**Comment by netojoaobatista** [comment]
Sim; definitivamente é o fato das aspas estarem dobradas; pense assim: o json é o idioma que você conversa com a API; se você muda o idioma, a API não entende o que você está dizendo.

Basta resolver a questão das aspas dobradas e sua data, que está no formato inválido, que tudo vai funcionar.

:smile:

**Comment by felipeejunges** [comment]
A data é facil de resolver, estarei amanha tentando resolver o problema da aspas duplas, só medo de ser algo do VB.net mesmo kkkk

**Comment by netojoaobatista** [comment]
Vou manter a issue aberta então. Se precisar, volte a comentar aqui.

:smile:

**Comment by felipeejunges** [comment]
Então, não acho que seja o json o problema, pois ajeitei o formato da data e testei criando uma aplicação do tipo console, convertendo os dados para json e imprimindo, sendo assim, o json foi impresso da forma correta (aparentemente).
![jsonprint](https://user-images.githubusercontent.com/20795458/29820810-16d70dac-8c9c-11e7-8cb7-38cf8b6318f5.png)

**Comment by netojoaobatista** [comment]
Seu JSON está correto; qual a resposta da API?

![image](https://user-images.githubusercontent.com/273586/29821255-a5c5a522-8c9d-11e7-98b4-9a36d0cada1a.png)

**Comment by felipeejunges** [comment]
![image](https://user-images.githubusercontent.com/20795458/29821310-d6a8223c-8c9d-11e7-9f56-a80bba1432b1.png)

Utilizando o Soap Ui funciona corretamente, mas no código vb

**Comment by netojoaobatista** [comment]
Então sabemos com certeza absoluta que o problema é no código VB; é que VB realmente não é minha praia, então vou escrever em C#; mas vamos isolar o código em partes para ver se encontramos o problema:

```csharp
HttpWebRequest request = (HttpWebRequest)WebRequest.Create ("https://apisandbox.cieloecommerce.cielo.com.br/1/sales/");

request.Method = "POST";
request.ContentType = "application/json";
request.Headers ["MerchantId"] = "MID";
request.Headers ["MerchantKey"] = "MKEY";

string json = @"{
    ""MerchantOrderId"": ""1234123"",
    ""Customer"": {
        ""name"": ""teste""
    },
    ""Payment"": {
        ""Type"": ""CreditCard"",
        ""Amount"": 1.0,
        ""Installments"": 1,
        ""SoftDescriptor"": """",
        ""CreditCard"": {
            ""CardNumber"": ""12312312"",
            ""Holder"": ""teste"",
            ""ExpirationDate"": ""12/2022"",
            ""SecurityCode"": ""1212"",
            ""Brand"": ""Visa""
        }
    }
}";

using (var writer = new StreamWriter (request.GetRequestStream ())) {
	writer.Write (json);
	writer.Close ();
}

HttpWebResponse response = (HttpWebResponse)request.GetResponse ();

var encoding = UTF8Encoding.UTF8;
using (var reader = new System.IO.StreamReader (response.GetResponseStream (), encoding)) {
	string responseText = reader.ReadToEnd ();

	Console.Write (responseText);
}
```

**Comment by felipeejunges** [comment]
Tenho impressão que é algo nas minha forma de conexão, pelo servidor estar rejeitando.

**Comment by felipeejunges** [comment]
Estarei adaptando seu código para vb durante a tarde :)

**Comment by felipeejunges** [comment]
Adaptei seu código para o baixo e continua não funcionando.
O erro acontece na linha Dim response As HttpWebResponse = request.GetResponse

E segue a imagem do navegador com analise de rede
![chrome](https://user-images.githubusercontent.com/20795458/29835777-5ffe24e8-8cc9-11e7-94b3-6fe3e7dc6dfc.png)


Aparentemente não está saindo nem do meu "servidor"

`

    Public Function postDados3(json As String, baseUrl As String, postUrl As String, merchant As Merchant)
        Dim urlPost As String = baseUrl & postUrl
        Dim jsonVolta As String

        Dim request As HttpWebRequest = WebRequest.Create(urlPost)

        request.Method = "POST"
        request.ContentType = "application/json"
        request.Headers("MerchantId") = merchant.id
        request.Headers("MerchantKey") = merchant.key

        Using writer = New StreamWriter(request.GetRequestStream())
            writer.Write(json)
            writer.Close()
        End Using

        Dim response As HttpWebResponse = request.GetResponse

        Dim encoding = UTF8Encoding.UTF8
        Using reader = New System.IO.StreamReader(response.GetResponseStream(), encoding)
            jsonVolta = reader.ReadToEnd()
        End Using

        Return jsonVolta


    End Function


`

**Comment by netojoaobatista** [comment]
Qual a versão do framework você está usando? Porque é obrigatório que a requisição utilize TLS 1.2.

**Comment by felipeejunges** [comment]
Então, esta funcionando agora. Eu forcei a utilização do Tls1.2 (aparentemente meu framework é 4.5)

Alteração:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

Código completo:
`

    Public Function postDados3(json As String, baseUrl As String, postUrl As String, merchant As Merchant) As String
        Dim urlPost As String = "https://apisandbox.cieloecommerce.cielo.com.br/1/sales/"
        Dim jsonVolta As String

        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12

        Dim request As HttpWebRequest = WebRequest.Create(urlPost)

        request.Method = "POST"
        request.ContentType = "application/json"
        request.Headers("MerchantId") = merchant.id
        request.Headers("MerchantKey") = merchant.key


        Using writer = New StreamWriter(request.GetRequestStream())
            writer.Write(json)
            writer.Close()
        End Using

        Dim response As HttpWebResponse = request.GetResponse

        Dim encoding = UTF8Encoding.UTF8
        Using reader = New System.IO.StreamReader(response.GetResponseStream(), encoding)
            jsonVolta = reader.ReadToEnd()
        End Using

        Return jsonVolta


    End Function

`

**Comment by netojoaobatista** [comment]
Então era isso; o 4.6 já tem TLS 1.2 como padrão; na 4.5 tem que especificar o 1.2. Valeu pelo código completo!

:smile:

**Comment by felipeejunges** [comment]
Só mais uma duvida, como deve ser passado o Master Card 2?

**Comment by netojoaobatista** [comment]
Não sei se entendi sua pergunta, mas se for o nome do emissor, os válidos são:

* Visa
* Master
* Amex
* Elo
* Aura
* JCB
* Diners
* Discover
