### ISSUE TITLE
Url da api não está funcionando

### ISSUE THREAD

**Issue by erickmajor** [DeveloperCielo/Webservice-3.0#33]
Boa tarde,

As Url´s https://sandbox.cieloecommerce.cileo.com.br/public/v1/orders e https://apiquerysandbox.cieloecommerce.com.br/public/v1/orders não estão funcionando.

Poderiam verificar, por favor?

#1

**Comment by netojoaobatista** [comment]
Esse `/public` aí não existe. As url corretas estão especificadas [no manual](https://developercielo.github.io/Webservice-3.0/#visão-geral---api-cielo-ecommerce)

**Comment by erickmajor** [comment]
Entendido @netojoaobatista 

Mas ainda assim não estão funcionando, retornando erro 404.

Além disso, mantive esse endereço por conta da Collection que disponibilizaram para fazer acesso via Postman, conforme disponibilizado [aqui](https://developercielo.github.io/Tutorial//Postman#importando-uma-collection).

**Comment by netojoaobatista** [comment]
Na collection do postman também não tem esse `/public`. As urls corretas estão especificadas  [no manual](https://developercielo.github.io/Webservice-3.0/#visão-geral---api-cielo-ecommerce). A imagem abaixo mostra que o serviço está funcionando corretamente; basta utilizar as utls corretas.

![image](https://user-images.githubusercontent.com/273586/29891570-f65e3d32-8da1-11e7-98b2-e0d709a925a3.png)

**Comment by erickmajor** [comment]
Obrigado pela rápida resposta @netojoaobatista 

Realmente o [endpoint sales](https://apisandbox.cieloecommerce.cileo.com.br/1/sales) funciona corretamente, como vc reportou.

Peço desculpas por não ter especificado antes, porém estou utilizando a collection para pagamentos via checkout. Nela a URL de Sandbox não funciona? Somente há a opção de testá-la com a URL de produção?

Mais uma vez obrigado.

**Comment by netojoaobatista** [comment]
Então:

1. Você está no repositório errado; abra sua issue no repositório do [Checkout Cielo](https://github.com/DeveloperCielo/Checkout-Cielo/issues)
2. Não existe esse endpoit de sandbox no Checkout Cielo; veja no manual sobre como utilizar o [modo de teste do Checkout Cielo](https://developercielo.github.io/Checkout-Cielo/#modo-de-teste-do-checkout-cielo)
