### ISSUE TITLE
Sandbox retornando status 415 no Android

### ISSUE THREAD

**Issue by endoooo** [DeveloperCielo/Webservice-3.0#35]
estamos no meio do desenvolvimento de um app para as plataformas Android e iOS, e essa semana começamos a receber um retorno 415 da API sandbox, porém **somente em requisições realizadas por devices Android** (no iOS, seja emulador ou device, não acontece o erro).

como este problema surgiu sem alterarmos o código do app, e dado o tipo do status retornado (415 = Unsupported Media Type) ficamos com uma dúvida: recentemente foi realizada alguma alteração em relação ao formato do payload suportado?

no aguardo. muito obrigado!

**Comment by endoooo** [comment]
informação que talvez ajude: estamos desenvolvendo em React Native, e por isso não utilizamos as SDKs oferecidas

**Comment by netojoaobatista** [comment]
@endoooo, o 415 é porque o `Content-Type` não está sendo reconhecido. Duas questões:

1. Variaram o dispositivo ou emulador do Android, de forma que a versão, seja do sistema operacional, seja do React, tenha mudado?
2. Como, exatamente, está o header `Content-Type`? Consegue obter um trace completo da requisição, com headers e body?

**Comment by endoooo** [comment]
@netojoaobatista seguem respostas:

1. não variaram, nem versão do OS nem o do React (não fizemos nenhuma atualização do código)

2. o RN tem um problema em relação ao tracing das requisições de rede, então neste ponto fico devendo um trace **completão**, mas consigo lhe passar o que estamos configurando manualmente nas requisições (que é o que eu pego no Reactotron):

```javascript
// header
{
  'Content-Type': 'application/json',
  'MerchantId': '********',
  'MerchantKey': '********',
}

// body
{
  MerchantOrderId: '********',
  {
    Payment: {
      Type: 'CreditCard',
      Amount: 1380,
      Installments: 1,
      CreditCard: {
        CardToken: '********',
        SecurityCode: '***',
        Brand: '********',
    }
  }
}
```

endpoint: `https://apisandbox.cieloecommerce.cielo.com.br/1/sales`

e sobre o seu comentário:

> o 415 é porque o Content-Type não está sendo reconhecido

sim, desconfiamos disso aqui. o problema é que, no iOS, com estes mesmos request headers e body, a chamada retorna 200... estranho não?

**Comment by netojoaobatista** [comment]
> sim, desconfiamos disso aqui. o problema é que, no iOS, com estes mesmos request headers e body, a chamada retorna 200... estranho não?

Sim; fiz um teste nesse momento utilizando o Postman e obtive um 500. Estou verificando aqui sobre alguma possível indisponibilidade do Sandbox.

**Comment by netojoaobatista** [comment]
@endoooo, parece que houve algum deploy que pode ter ocasionado a quebra; se enviarmos a requisição completa, recebemos o 201 como esperado; consegue fazer outro teste amanhã? Aí vemos se o problema é apenas temporário, de invalidação de cache ou algo parecido, ou se é algo com o contrato em si.

**Comment by endoooo** [comment]
@netojoaobatista testei agora e voltou a funcionar 🎉 

vou fechar a issue. se o problema voltar eu abro novamente.

muito obrigado pelo suporte!
