### ISSUE TITLE
Create Credit Card Token

### ISSUE THREAD

**Issue by arkadyzalko** [DeveloperCielo/Webservice-3.0#4]
Hello,

Congrats to documentation, it's really great! But I not found any information about card token creation.

Please, can you inform how to create credit card token using Webservice 3.0?

Thank you

**Comment by netojoaobatista** [comment]
Please, take a look at [Creating a sale with Card Token](http://developercielo.github.io/Webservice-3.0/english.html#creating-a-sale-with-card-token).
