### ISSUE TITLE
Classes "FraudAnalisys" e "FraudAnalysis"

### ISSUE THREAD

**Issue by davidcoimbra** [DeveloperCielo/Webservice-3.0#5]
Percebi que existem duas classes descritas na resposta da analise de fraudes. Uma com o nome de "FraudAnalisys" e outra "FraudAnalysis", com uma simples diferença no Y. Isso é um erro de documetação ou é a real resposta da API?

**Comment by netojoaobatista** [comment]
Aparentemente é um typo; vou verificar a resposta correta e providenciar os ajustes necessários.

**Comment by netojoaobatista** [comment]
@davidcoimbra, apenas para avisar, isso já está em análise para correção.

:smile:

**Comment by davidcoimbra** [comment]
Legal otimo! obrigado por avisar
