### ISSUE TITLE
Correção do endPoint da SandBox

### ISSUE THREAD

**Issue by ederlopes** [DeveloperCielo/Webservice-3.0#6]
Bom dia, 
Favor corrigir endPoint na documentação exemplo de código do cURL
 
DE:    --request POST "https://sandbox.cieloeCommerce.cielo.com.br/1/sales/"
Para: --request POST "https://apisandbox.cieloeCommerce.cielo.com.br/1/sales//"

**Comment by mayararomao** [comment]
já foi corrigido

**Comment by mozgbrasil** [comment]
Ola

Boa Tarde

Nos exemplos em CURL ainda tem esse erro

Em

https://developercielo.github.io/Webservice-3.0/?shell#criando-uma-venda-com-autentica%C3%A7%C3%A3o

Temos

    curl
    --request POST "https://sandbox.cieloecommerce.cielo.com.br/1/sales/"

deveria estar como 

    curl
    --request POST "https://apisandbox.cieloecommerce.cielo.com.br/1/sales/"
