### ISSUE TITLE
Sandbox para Transferência Online e Cartão de Débito

### ISSUE THREAD

**Issue by loja5combr** [DeveloperCielo/Webservice-3.0#7]
Ola, estou desenvolvendo uma aplicação em php usando a api 3.0 onde em transferência e cartão de débito esta retornando alguns problemas, cartão de crédito e boleto esta funcionando corretamente.

**Em transferência online envio (de acordo manual):**
{"MerchantOrderId":"452","Customer":{"Name":"teste a\u00e7\u00f5es a\u00e7enos"},"Payment":{"Type":"EletronicTransfer","Amount":"10000","Provider":"Bradesco","ReturnUrl":"http:\/\/localhost\/opencart22\/index.php?route=payment\/braspag5tef\/ipn&id=452&hash=d2688fcaee88821fbaeb7b6cf5fdd002e8f6392e"}}
**Mas sempre retorna:**
"Code": 133,    "Message": "Provider is not supported for this Payment Type" 

**E em cartão de débito:**
{"MerchantOrderId":"453","Customer":{"Name":"teste a\u00e7\u00f5es a\u00e7enos","Email":"msn@loja5.com.br"},"Payment":{"Type":"DebitCard","Amount":"10000","ReturnUrl":"http:\/\/localhost\/opencart22\/index.php?route=payment\/braspag5debito\/ipn&id=453&hash=0f06854b2e744625faabeaafa2e4e903e1ece962","DebitCard":{"CardNumber":"4551870000000183","Holder":"TESTE A\u00c7\u00d5ES A\u00c7ENOS","ExpirationDate":"02\/2018","SecurityCode":"122","Brand":"Visa"}}}
**E retorna:**
"Code": 133,    "Message": "Provider is not supported for this Payment Type"

Existe alguma limitação para estes dois métodos em sandbox?

**Comment by netojoaobatista** [comment]
@loja5combr, apenas operação de crédito está disponível no [sandbox](https://developercielo.github.io/Webservice-3.0/#sandbox).

**Comment by loja5combr** [comment]
@netojoaobatista Obrigado, mas saberia informar se isso é algo de momento ou sempre será assim?

**Comment by netojoaobatista** [comment]
Está no planejamento permitir testes de outros meios de pagamento no sandbox, mas ainda não tem uma data definida da disponibilidade.

**Comment by loja5combr** [comment]
@netojoaobatista Certo, obrigado pelas informações.

**Comment by netojoaobatista** [comment]
:smile:
