### ISSUE TITLE
Códigos de Retorno

### ISSUE THREAD

**Issue by m98proxy** [DeveloperCielo/Webservice-3.0#8]
Quais são todos os códigos de retorno, pergunto isto porque na documentação diz que 

`4	Operação realizada com sucesso`

Porém na realidade o código de sucesso que chega no JSON de resposta é **6**

fonte: https://developercielo.github.io/Webservice-3.0/?shell#sandbox

**Comment by netojoaobatista** [comment]
@m98proxy, isso está ocorrendo no Sandbox, correto?

Estou subindo uma tabela agora com os códigos de retorno em produção; verei sobre os códigos de retorno com o cartão simulado ainda hoje.

**Comment by m98proxy** [comment]
Sim @netojoaobatista na Sandbox, o problema é que lá é o único ambiente que tenho para testes né man? Então não tenho como afirmar pra você se acontece em produção também.

**Comment by netojoaobatista** [comment]
Lógico; você está certo.

Consegue, por favor, me mandar o retorno completo?

**Comment by avilardo** [comment]
Pessoal, o erro persiste no ambiente de SANDBOX!

Ao efetuar testes de transação com sucesso no ambiente de SANDBOX tenho receibido o retrunCode como 6 ao invés de 4 como consta na documentação da API (https://developercielo.github.io/Webservice-3.0/).

Sabem me informar se a documentação esta desatualizada ou é o ambiente de SANDBOX que não retorna 4 como "Successful Operation"?
