### ISSUE TITLE
Tipos de bandeiras e seus códigos

### ISSUE THREAD

**Issue by mozgbrasil** [DeveloperCielo/Webservice-3.0#9]
Ola, Boa Tarde

Quais as bandeiras e seus códigos que posso utilizar no uso de cartão de débito

Na documentação em

https://developercielo.github.io/Webservice-3.0/#criando-uma-venda-simplificada27

Não tem a informação de bandeiras de cartão de débito

Tem a informação de bandeiras de cartão de crédito

Bandeira do cartão (Visa / Mastercard / Amex / Elo / Auria / JCB / Diners / Discover)

Outra questão o correto não seria Aura, porque na documentação está como Auria

**Comment by netojoaobatista** [comment]
Olá @mozgbrasil,

> Não tem a informação de bandeiras de cartão de débito
> 
> Tem a informação de bandeiras de cartão de crédito
> 
> Bandeira do cartão (Visa / Mastercard / Amex / Elo / Auria / JCB / Diners / Discover)

Para cartão de **débito**, apenas Visa e Master; as grafias são as mesmas do crédito, mas apenas Visa e Master estão disponíveis na modalidade débito.

> Outra questão o correto não seria Aura, porque na documentação está como Auria

Um typo.
